### ISSUE TITLE
Installation on Ubuntu 14.10

### ISSUE THREAD

**Issue by hakonhagland** [pknowles/cropall#1]
Hi, I am about to test the `cropall.py` script on Ubuntu 14.10. 

For your information, here is what I had to do to get it running:
- Cloned with `git clone https://github.com/pknowles/cropall.git`
- Changed shebang of `cropall.py` from  `#!/bin/python` to `#! /usr/bin/env python2`
- installed python-tk : `sudo apt-get install python-tk`
- installed python-imaging-tk : `sudo apt-get install python-imaging-tk`
- run script from terminal window with `./cropall.py`

Maybe this info should be added to `README.md` ?

**Comment by pknowles** [comment]
Cheers @hakonhagland. Much appreciated!
