### ISSUE TITLE
Error: no resize specified. Not resizing

### ISSUE THREAD

**Issue by stueja** [pknowles/cropall#10]
The error can be avoided by replacing line 392
```
c += " -resize \"" + str(resize_width) + "x" + str(resize_height) + ">\""
```

against
```
		if (resize_width > 0):
			c += " -resize \"" + str(resize_width) + "x" + str(resize_height) + ">\""
		c += " \"" + os.path.join(self.outDir, self.currentName) + "\""
```

**Comment by pknowles** [comment]
[edit] thanks for reporting this!

IIRC, this error is only in the resize-only path. E.g. if the resize button is clicked but the width/height are invalid then skipping the resize portion would result in a no-op anyway. For that there is the copy button. Maybe the solution here is that should be implicit?

**Comment by pknowles** [comment]
I've changed the way this wors now, deleting those lines in https://github.com/pknowles/cropall/pull/12/commits/eecd1ee11786c2c99765b62f4e43a49e031014cb

The resize resolution is now in the GUI and always valid. Clicking "Resize" always resizes. There's now an extra option to resize after cropping.
