### ISSUE TITLE
Fork specifically for book scanning

### ISSUE THREAD

**Issue by rystraum** [pknowles/cropall#2]
I just wanted to let you know that I made a fork of your code, and modified it to accommodate cropping scans of books. I feel like it does not have a place in your repo because you wrote this specifically for a different kind of workflow but feel free to pull in my changes.

The following changes have been done:
- Changed the bounding box from yellow to red
- A much more granular "zooming" factor
- Key-bindings for arrow keys, and ctrl+arrow keys
- <coming soon> key binding for rotating
- <coming soon> deskewing before cropping

Thank you for sharing your work. I found your repo from your answer in this question: http://askubuntu.com/questions/97695/is-there-a-lightweight-tool-to-crop-images-quickly

PS. That person that commented on your answer was a bit of an a**.

**Comment by pknowles** [comment]
Cheers. Glad it's useful. Will add a link to your fork.
